Implement payload contains filtering
honeynet/ochi pull request #57
Opened 2023-07-02 23:34 UTC by dkumiszhan

The new query can be used like this:
```
payload contains "test"
```

2023-07-03 10:05 UTC, glaslos requested changes

2023-07-03 10:05 UTC, glaslos commented on src/eventFilter.ts
> +        return event.payload.toLowerCase().includes(trimmedString);
The `payload` field is base64 encoded, you would need to [decode](https://github.com/honeynet/ochi/blob/main/src/components/Content.svelte#L6) it here for string matching.

2023-07-03 10:05 UTC, glaslos commented on src/eventFilter.ts
> +        let payloadString = children.searchClause[0].children.STRING[0].image.toLowerCase();
In the future we should consider making this case sensitive

2023-07-03 10:05 UTC, glaslos commented on src/dsl.ts
> +const string = createToken({ name: 'STRING', pattern: /\"[a-zA-Z0-9]+\"/ });
We should consider adding special characters here as well, letters and digits should be fine for now.

2023-07-05 15:26 UTC, dkumiszhan commented on src/eventFilter.ts
> +        return event.payload.toLowerCase().includes(trimmedString);
done

2023-07-05 15:26 UTC, dkumiszhan commented on src/eventFilter.ts
> +        let payloadString = children.searchClause[0].children.STRING[0].image.toLowerCase();
done

2023-07-06 09:16 UTC, merged